[package]
name = "kit-desktop-slint"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"]}
serde = "1.0.219"
slint = "1.10.0"
tokio = { version = "1.44.2", features = ["rt-multi-thread"]}

[build-dependencies]
slint-build = "1.8.0"
